options {
   
        directory "/var/named";
        dnssec-validation no;
        recursion yes;
        allow-query { any; };
        };

zone "web1.local" {
 		      type master;
                      file "web1";
                  };

zone "web2.local" {
  	 	     type master;
		     file "web2";
		  };

zone "urban.com" {
		      type master;
		      file "urban";
	         };

zone "rural.com" {
		      type master;
		      file "rural";
	         };


